booksite/bookapp/urls.py
from django.contrib import admin
from django.urls import path
from bookapp import views


app_name = 'bookapp'
urlpatterns = [

    path('index/',views.index,name='index'),
    path('book/<int:book_id>/',views.detail,name='detail'),
    path('add/',views.add_book,name='add_book'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

booksite/booksite/urls.py
from django.contrib import admin
from django.urls import path,include
from bookapp import views
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookapp.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

booksite/bookapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.IntegerField()
    book_image = models.ImageField(default='default.img',upload_to='book_images/')

booksite/bookapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name','author','book_image','price']

booksite/bookapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Book
from .forms import BookForm


# Create your views here.
def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list':book_list
    }

    return render(request,'bookapp/index.html',context)

def detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request,'bookapp/detail.html',{'book':book})
def add_book(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        author = request.POST.get('author',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']

        book = Book(name=name,author=author,price=price,book_image=book_image)
        book.save()

    return render(request,'bookapp/add_book.html')
def update(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/index/')
    return render(request,'bookapp/edit.html',{ 'form':form,'book':book})
def delete(request,id):
    if request.method == "POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/index/')
    return render(request,'bookapp/delete.html')

booksite/bookapp/templates/bookapp/add_book.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" id="name" placeholder="enter a book name">
    <input type="text" name="author" id="author" placeholder="enter a book author">
    <input type="text" name="price" id="price" placeholder="enter a book price">
    <input type="file" name="book_image" id="book_image">
    <input type="submit" name="" id="">

</form>

booksite/bookapp/templates/bookapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bookapp/style.css' %}">
</head>
<body>
     <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
         BooK Store
        </a>
      </nav>
      {% block body %}


      {% endblock %}


</body>
</html>

booksite/bookapp/templates/bookapp/delete.html
<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are u suire, you eant to delete this Book
    <input type="submit" >

</form>

booksite/bookapp/templates/bookapp/detail.html
{% extends 'bookapp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img width="100" height="100" src="{{book.book_image.url}}">
        </div>
        <div class="col-md-6">
            Book Name : <h2>{{ book.name }}</h2><br>
            Book author : <h4>{{ book.author }}</h4><br>
            Price : <h6>{{ book.price }}</h6><br>
            <a class ="btn btn-warning" href="{% url 'bookapp:update' book.id %}">Update</a>
            <a class ="btn btn-danger" href="{% url 'bookapp:delete' book.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock%}

booksite/bookapp/templates/bookapp/edit.html
<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name=""id="">

</form>

booksite/bookapp/templates/bookapp/index.html
{% extends 'bookapp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for book in book_list %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{book.book_image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">BOOK : {{book.name}}</h5>
                    <a class="btn btn-warning" href="{% url 'bookapp:detail' book.id %}">view details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}